
import { Itinerary } from "@/components/ItineraryDisplay";

const generatePDF = (itinerary: Itinerary): void => {
  // In a real implementation, this would use a library like jsPDF or react-pdf
  // For now, we'll create a simple HTML-based printable version
  
  const printWindow = window.open('', '_blank');
  
  if (!printWindow) {
    alert('Please allow popups to generate the PDF');
    return;
  }
  
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${itinerary.title}</title>
      <style>
        body {
          font-family: 'Arial', sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 2px solid #1e593b;
        }
        h1 {
          color: #1e593b;
          margin-bottom: 10px;
        }
        .dates {
          font-size: 18px;
          color: #666;
        }
        .day-card {
          margin-bottom: 30px;
          border: 1px solid #ddd;
          border-radius: 5px;
          overflow: hidden;
        }
        .day-header {
          background-color: #1e593b;
          color: white;
          padding: 10px 15px;
        }
        .day-content {
          padding: 15px;
        }
        .activity-time {
          font-weight: bold;
          color: #1a7b99;
          min-width: 80px;
          display: inline-block;
        }
        .section-title {
          color: #1e593b;
          border-bottom: 1px solid #eee;
          padding-bottom: 5px;
          margin-top: 15px;
        }
        .footer {
          text-align: center;
          margin-top: 50px;
          font-size: 14px;
          color: #666;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${itinerary.title}</h1>
        <div class="dates">${itinerary.dates.start} to ${itinerary.dates.end}</div>
      </div>
      
      ${itinerary.days.map(day => `
        <div class="day-card">
          <div class="day-header">
            <h2>Day ${day.day}: ${day.location}</h2>
            <div>${day.date}</div>
          </div>
          <div class="day-content">
            <h3 class="section-title">Activities</h3>
            <ul>
              ${day.activities.map(activity => `
                <li><span class="activity-time">${activity.time}</span> ${activity.description}</li>
              `).join('')}
            </ul>
            
            ${day.meals ? `
              <h3 class="section-title">Meals</h3>
              <ul>
                ${day.meals.breakfast ? `<li><span class="activity-time">Breakfast</span> ${day.meals.breakfast}</li>` : ''}
                ${day.meals.lunch ? `<li><span class="activity-time">Lunch</span> ${day.meals.lunch}</li>` : ''}
                ${day.meals.dinner ? `<li><span class="activity-time">Dinner</span> ${day.meals.dinner}</li>` : ''}
              </ul>
            ` : ''}
            
            <h3 class="section-title">Accommodation</h3>
            <p>${day.accommodation}</p>
            
            ${day.notes ? `
              <h3 class="section-title">Notes</h3>
              <p>${day.notes}</p>
            ` : ''}
          </div>
        </div>
      `).join('')}
      
      <div class="footer">
        <p>Generated by Kerala Trip Planner AI - ${new Date().toLocaleDateString()}</p>
      </div>
      
      <script>
        window.onload = function() {
          window.print();
        }
      </script>
    </body>
    </html>
  `);
  
  printWindow.document.close();
};

export default generatePDF;
